name: Sok-1400
title: null
undertitle: Introduksjon til python
bilde: https://github.com/paspvik/plainside/blob/gh-pages/assets/img/py.png?raw=true
bakgrunn: https://github.com/paspvik/plainside/blob/gh-pages/assets/img/background.jpg?raw=true
