name: SOK-1004 Økonomiske emner og programmering
title: null
undertitle: 
bilde: https://www.r-project.org/logo/Rlogo.png
bakgrunn: https://github.com/paspvik/plainside/blob/gh-pages/assets/img/background.jpg?raw=true
